version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/skills
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
